### ISSUE TITLE
Configurar dominio para o site

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#2]
Atualmente este site esta operando diretamente na IP. Precissamos de configurar um domínio e apuntá-lo

**Comment by ogecece** [comment]
Alias criado de minutas.ok.org.br e www.minutas.ok.org.br para o IP da máquina @basicavisual

**Comment by categulario** [comment]
Hi @giuliocc ! In order to obtain the certificate for this domain, could you provide me with an email from someone on your side that will be used to register the Let's Encrypt account?

This email will receive domain expiration alerts (which won't really happen because the renewal happens automatically).

Thank you.

**Comment by ogecece** [comment]
Sure! contato@ok.org.br can be used for this @categulario

**Comment by categulario** [comment]
Me es un placer informar que el sitio ya es accesible por medio de la dirección https://minutas.ok.org.br .
